### ISSUE TITLE
Hỏi anh vài câu...

### ISSUE THREAD

**Issue by thethanh02** [28dec/qldt_prepare_schedule#2]
Cho hỏi tool còn hoạt động k ạ và có an toàn k :>

**Comment by AdvMaple** [comment]
> Cho hỏi tool còn hoạt động k ạ và có an toàn k :>

Còn hoạt động bạn nhé.

**Comment by 28dec** [comment]
1. về câu hỏi có hoạt động không, thì hiện tại vẫn chạy tốt nhé em. QLDT vừa thay đổi format, nhưng anh cũng fix luôn rồi.
2. về câu hỏi có an toàn không, thì cái này khá khó nói. Về phía anh là tác giả của script này, thì động cơ để anh bắt đầu và duy trì script là để giúp đỡ mọi người xếp lịch được dễ dàng hơn. Còn thực tế, thì đừng tin bố con thằng nào em ạ, phải đọc source code xem thằng tác giả nó viết cái gì trong đó thì mới nói được là có an toàn không 😄
